### PR TITLE
[DOCUMENTATION] Add new YT channel in README

### PR DESCRIPTION
**Pull request by Rahul-Prasad-07**
## 👨‍💻 Changes proposed
Add the YT Channel of [Code Eater](https://www.youtube.com/c/EatTheBlocks) for Indian folks (Hindi Lang)  in README.md file

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Kindly review it and merge my PR. I'd be happy to contribute to this repository as my first step while getting into the world of Web3 and Open source contribution.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Rahul-Prasad-07 It's a duplicate PR

**Comment by ewainy** [comment]
Thanks for flagging @Susmita-Dey. I see that the link in the PR message takes me to EatTheBlocks, but the actual commit in the file takes me to the right channel so its all good! :)

**Review by ewainy — APPROVED** [review]
Thank you for the addition, this will be helpful to a lot of people :)

**Review by Susmita-Dey — COMMENTED** [review]
You haven't created any issue for that. You have linked my PR to yours.
READ the `CONTRIBUTING.md` file

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
@ewainy Issues have not been created for this PR.

**Comment by ewainy** [comment]
> @ewainy Issues have not been created for this PR.

This is true and it is best practice to do so, I have been guilty of doing this myself.

**Comment by Rahul-Prasad-07** [comment]
I apologize for that .I will be more careful from now. @Susmita-Dey @ewainy

**Review by FrancescoXX — APPROVED** [review]

**Comment by Rahul-Prasad-07** [comment]
Thank you so much @FrancescoXX  for accepting my PR as Hacktoberfest 2022.
I am very happy to contribute :)

**Pull request merged**
