### PR TITLE
I added a free polygon bootcamp

### PR DESCRIPTION
**Pull request by Tani1964**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Tani1964** [comment]
please include a free polygon bootcamp, Thank you

**Review by Atharv181 — APPROVED** [review]
LGTM

**Review by Atharv181 — APPROVED** [review]
Thank you

**Comment by Tani1964** [comment]
you're wecolme

**Comment by FrancescoXX** [comment]
please don't add resources to the html file

**Pull request merged**
