### PR TITLE
Footer section has been set to center successfully

### PR DESCRIPTION
**Pull request by SoumyadeepOSD**
# Before changes was done👇
- <h3>Footer elements was not in center</h3>
footer_prev

# After adding the changes👇
- <h3>Footer elements are set to center</h3>
footer_modify

### CODE REVIEW

**Comment by tobySolutions** [comment]
This is the mobile view of your fix @SoumyadeepOSD. Can you see to this please?

**Comment by SoumyadeepOSD** [comment]
> This is the mobile view of your fix @SoumyadeepOSD. Can you see to this please?

Yes @tobySolutions , I'm looking into the matter

**Comment by tobySolutions** [comment]
Awesome @SoumyadeepOSD!!!

**Comment by tobySolutions** [comment]
Any updates @SoumyadeepOSD?

**Comment by SoumyadeepOSD** [comment]
> Any updates @SoumyadeepOSD?

Don't worry @tobySolutions. I'll fix this issue by tomorrow. Just give me one day (as my college exams are going on)✌️

**Comment by FrancescoXX** [comment]
good luck @SoumyadeepOSD

**Comment by tobySolutions** [comment]
Goodluck @SoumyadeepOSD!!

**Comment by tobySolutions** [comment]
Hey @SoumyadeepOSD let me check it out.

**Comment by tobySolutions** [comment]
Awesome!! Looks awesome!!

**Comment by SoumyadeepOSD** [comment]
@tobySolutions  thanks for merging my PR😁

**Pull request merged**
