### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yashdev9274**
Updated the layout of readme and added "Top 10 Blockchain Network for developer"  Now it looks good

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by yashdev9274** [comment]
Please except this PRs , if you don't look still, I will make changes on the go as per you wish. 
I Updated the layout of readme and added "Top 10 Blockchain Network for developer" 
which will make it look good

**Review by Atharv181 — COMMENTED** [review]
Can you take screenshot and show us

**Review by PatelYash07 — APPROVED** [review]

**Comment by yashdev9274** [comment]
> Can you take screenshot and show us

I couldn't take screenshots of the changes, but I'll provide the presentation view today.

**Comment by yashdev9274** [comment]
image

here is how a updated the readme file

**Comment by yashdev9274** [comment]
Is anyone reviewing this PR?

**Comment by FrancescoXX** [comment]
hey @yashdev9274 it seems many changes have been done here, do you mind solving the conflicts please?

**Comment by yashdev9274** [comment]
yeah sure I'll. Thank you for reply @FrancescoXX .

**Comment by tobySolutions** [comment]
Awesome @yashdev9274!!!

**Pull request closed without merging**
