### PR TITLE
Add Feature Ethereum Development Resources

### LINKED ISSUE #68: Add Ethereum Development Tools
Add resources/tools used in Ethereum Development

### PR DESCRIPTION
**Pull request by geniusyinka**
this pull request Adds Ethereum development resources. 

## 🛠️ Fixes Issue

closes #68

## 👨‍💻 Changes proposed

Addition of Ethereum development resources

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by ewainy — COMMENTED** [review]
Great additions! :) Scaffoldeth.io times out for me though, I can't load the link :(  
I will need someone else to take a look, Francesco will probably review on an upcoming live stream.

**Comment by geniusyinka** [comment]
> Great additions! :) Scaffoldeth.io times out for me though, I can't load the link :( I will need someone else to take a look, Francesco will probably review on an upcoming live stream.

thank you! scaffoldeth.io seems to work fine for me. hehe, will be on the lookout for the review!

**Review by MarineNewt — CHANGES_REQUESTED** [review]
I am also having trouble accessing the scaffoldeth.io link as pasted in your request: getting an error returning webpage timed out. Seems to likely be an issue on their end, maybe their repository link would suffice till the site is straightened out? 

https://github.com/scaffold-eth/scaffold-eth

**Comment by geniusyinka** [comment]
> I am also having trouble accessing the scaffoldeth.io link as pasted in your request: getting an error returning webpage timed out. Seems to likely be an issue on their end, maybe their repository link would suffice till the site is straightened out?
> 
> https://github.com/scaffold-eth/scaffold-eth

ah, let's replace it with the github link, then

**Pull request merged**
