### PR TITLE
Docs add blockchain architecture modular monolithic

### PR DESCRIPTION
**Pull request by codewithuddy**
## 👨‍💻 Changes proposed
 - Adds a markdown file on Blockchain Architecture
 - Markdown contains link to an external detailed publication on Monolithic and Modular Blockchains

## 📄 Note to reviewers
Modular blockchain approach aids further understanding from the blockchain trilemma standpoint. <br>
I saw a detailed review on blockchain trilemma right here on the repository, it spurred me into sharing my publication on modular blockchains. 

This will indeed be a great material for anyone seeking to start out learning about blockchains and web3.0

### CODE REVIEW

**Comment by FrancescoXX** [comment]
how will this file be visualized?

**Comment by codewithuddy** [comment]
On how it will be visualised, I believe best results will be gotten from adding the .md doc to the main repo

**Review by FrancescoXX — CHANGES_REQUESTED** [review]
please add the changes in the Readme.md

**Comment by FrancescoXX** [comment]
@codewithuddy do you still want to work on this?

**Pull request merged**
