### PR TITLE
add GitHub icon that redirects to repository

### LINKED ISSUE #185: Add a wasy to redirect from the website to the GitHub repository
**Is your feature request related to a problem? Please describe.**
the generated website doesn't redirect to the GitHub repo

**Describe the solution you'd like**
out a GitHub icon somewhere in the file at the top to redirect to the GitHub repository

**Describe alternatives you've considered**
the icon and the positioning provided are just an example

image

### PR DESCRIPTION
**Pull request by Rishav-12**
## 🛠️ Fixes Issue
Closes #185 

## 👨‍💻 Changes proposed

- Added a GitHub icon next to the main heading
- It redirects back to the repo

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Please check if changes apply to the website

### CODE REVIEW

**Comment by Rishav-12** [comment]
It does apply to the website, I just deployed from my branch 👍🏽

**Comment by Rishav-12** [comment]
https://rishav-12.github.io/free-Web3-resources/

**Comment by FrancescoXX** [comment]
the functionality is ok, we need another issue to solve the icon being visible in both dark and light mode and being centered properly

**Comment by FrancescoXX** [comment]
closed by #190

**Pull request merged**
