### PR TITLE
Add a YouTube Video

### LINKED ISSUE #328: Add a Youtube Video
### 📚 Documentation

I have found a great resource that will help people become a Blockchain developer!

Title: How to Become a Blockchain Developer in 2023 (Roadmap)
Platform: Youtube
Link: https://www.youtube.com/watch?v=zglv3lCchSo

### Add relevant screenshot or video (if any)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sriparno08**
## 🛠️ Fixes Issue

Closes #328

## 👨‍💻 Changes proposed

I have added a useful YouTube video in the list of blockchain roadmaps!

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by ewainy — APPROVED** [review]
Amazing! Thank you for your changes and contribution :)

**Comment by tobySolutions** [comment]
Thanks @Sriparno08!1

**Comment by tobySolutions** [comment]
Fixes #338

**Comment by Sriparno08** [comment]
Thanks, maintainers! 😊

**Pull request merged**
