### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by muhammadanas0716**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by FrancescoXX** [comment]
funny but closed 😂😂😂

**Comment by Atharv181** [comment]
😆 😆

**Comment by muhammadanas0716** [comment]
Oh well no problem! Frans knows who I am. I did this for fun! Now I'll try to be more intuitive 😂

**Comment by Atharv181** [comment]
ohhk 😄 😄

**Pull request closed without merging**
