### PR TITLE
Added search option

### PR DESCRIPTION
**Pull request by suhailkakar**
## 🛠️ Fixes Issue
I have added a search option to the live version, so the users can directly search for any resources they want : )

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

https://user-images.githubusercontent.com/56798748/163710577-79002e2a-070f-4dc7-9405-496f8e7a777d.mov

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
LGTM!, This is a great addition, Suhail :rocket: 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Elegant

**Comment by JayrajSingh65** [comment]
Great work

**Review by krshdev — APPROVED** [review]
Wow this is awesome! It is a great addition to the project! Thanks for the contribution! And I really like that you recorded a demo and shared it 😍

**Comment by FrancescoXX** [comment]
I love the fact you add a video on each PR!

**Pull request merged**
