### PR TITLE
feat: light mode changes

### PR DESCRIPTION
**Pull request by rohinish404**
i have made some changes to the light mode but need some feedback.is the gray text looking okay or it should be more dark?
and should i also change the color of the navbar and footer in light mode??

### CODE REVIEW

**Comment by rohinish404** [comment]
Issue #405

**Comment by tobySolutions** [comment]
Great job @rohinish404!! Let me check it out. Amazing! 🚀🚀🚀

**Comment by rohinish404** [comment]
> Great job @rohinish404!! Let me check it out. Amazing! 🚀🚀🚀

Yeah sure @tobySolutions !!

**Comment by tobySolutions** [comment]
image


For the light mode, could you please make the navbar white as well? Also, the text color in Light mode needs to be darker. Great job @rohinish404. So sorry for the late response.

**Comment by rohinish404** [comment]
Oh no worries @tobySolutions . Yeah sure, i'll make the changes soon!!

**Comment by tobySolutions** [comment]
> Oh no worries @tobySolutions . Yeah sure, i'll make the changes soon!!

Awesome @rohinish404! I'll be expecting your updates!

**Comment by rohinish404** [comment]
ohk, so i made the overall text darker and changed the navbar color to white with black text inside it.
Is the gray bg on home page looking okay? or should i also change that to white??
Screenshot 2023-03-02 at 9 07 09 PM

**Comment by tobySolutions** [comment]
It looks amazing @rohinish404!! Great job!

**Comment by tobySolutions** [comment]
[Screencast from 03-02-2023 08:01:31 PM.webm](https://user-images.githubusercontent.com/96334363/222526272-1910f567-ab59-40cf-8d64-ba36f42fd859.webm)

The text color isn't changing with the theme changes. Can you check that out?

**Comment by rohinish404** [comment]
Yeah sure!! I'll make the desired changes.

**Comment by tobySolutions** [comment]
Great job @rohinish404!! There are still some minor issues with the sidebar on mobile.

**Comment by rohinish404** [comment]
> Great job @rohinish404!! There are still some minor issues with the sidebar on mobile.

Thank you @tobySolutions !! I'll try to resolve the remaining issues :)

**Comment by tobySolutions** [comment]
Awesome! Thanks Roshinish!

**Pull request merged**
