### PR TITLE
Update the Documentation

### PR DESCRIPTION
**Pull request by money8203**

### CODE REVIEW

**Comment by tobySolutions** [comment]
Could you add more details about the project in the Readme. This does not contain enough information about the project. @money8203.

Thank you!

**Comment by money8203** [comment]
As in what ? Can you reference some @tobySolutions !!

**Comment by tobySolutions** [comment]
Looks good now @money8203. Thanks for this!!

**Comment by tobySolutions** [comment]
Fixes issue #372

**Pull request merged**
